name: fyp_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.8.4
  open_file: ^3.3.2

  http: ^0.13.4
  lottie: ^2.2.0
  fluttertoast: ^8.0.9
  flutter_local_notifications: ^15.0.0
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  percent_indicator: ^4.2.3
  timezone: ^0.9.1
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  permission_handler: ^11.0.0
  share_plus: ^6.0.0
  image_picker: ^1.0.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  video_player: ^2.4.10
  flick_video_player: ^0.5.0
  sqflite: ^2.2.8+4
  uuid: ^3.0.6
  path_provider: ^2.0.15
  # line chart
  fl_chart: ^0.66.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  andriod: true
  ios: true
  image_path: "images/icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/3.jpg
    - images/1.jpg
    - images/2.jpg
    - images/food.jpg
    - images/7.jpg
    - images/8.jpg
    - images/9.jpg
    - images/10.jpg
    - images/4.jpg
    - images/bg3.png
    - images/5.png
    - images/11.jpg
    - images/bg2.png
    - images/b1.jpg
    - images/bg6.jpg
    - images/bg1.png
    - images/logo.png
    - images/c1.jpeg
    - images/f1.jpg
    - videos/video.mp4
    - videos/diet.mp4
    - images/lotieAnimation.json
    - images/r1.jpg
    - images/beefkabab.jpg
    - images/Caesarsalad.jpg
    - images/fruitchat.jpg
    - images/haleem.jpg
    - images/halwa.jpg
    - images/pakora.jpg
    - images/pasta.jpg
    - images/paye.jpg
    - images/shamiKabab.jpg
    - images/smothie.jpg
    - images/salad.jpg
    - images/tikka.jpg
    - images/margritaPizza.jpg
    - images/nihari.jpg
    - images/chesseburger.jpg
    - images/veggie.jpg
    - images/seekhkabab.jpg
    - images/fried.jpg
    - images/icecream.jpg
    - images/chiller.jpg
    - images/lemonade.jpg
    - images/nugguts.jpg
    - images/hotDog.jpg
    - images/guacamole.jpg
    - images/cake.jpg
    - images/tacos.jpg
    - images/wrap.jpg
    - images/salsa.jpg
    - images/fries.jpg
    - images/milkshake.jpg
    - images/sandwich.jpg
    - images/shawarma.jpg
    - images/pineapple.jpg
    - images/sticks.jpg
    - images/grilled.jpg
    - images/toast.jpg
    - images/jam.jpg
    - images/coldcoffe.jpg
    - images/chesseSandwich.jpg
    - images/kheer.jpg
    - images/channachat.jpg
    - images/chapli.jpg
    - images/lassi.jpg
    - images/alooparatha.jpg
    - images/karahi.jpg
    - images/sheer.jpg
    - images/egg.jpg
    - images/halfFried.jpg
    - images/chesseOmlete.jpg
    - images/logo1.png
    - images/diet.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
